### ISSUE TITLE
2023 archive

### ISSUE THREAD

**Issue by pinventado** [csufesj/csufesj.github.io#28]
Provide a link to past competitions. In this case, it is only the 2023 competition. All previous competitions will be stored in a subfolder with the year of the competition. For example, the 2023 competition website will be in the 2023 subfolder.

**Comment by emilycrowl** [comment]
HTML page created and placed link for it. Need to populate

**Comment by pinventado** [comment]
When making final commit that fixes this, try to close issue with the commit. See https://docs.devart.com/studio-for-sql-server/source-controlling-databases/associating-commits-with-github-issues.html

**Comment by fooledyouonce** [comment]
Close

**Comment by emilycrowl** [comment]
done!
